### ISSUE TITLE
Mods Lookup Failing

### ISSUE THREAD

**Issue by rmgirardin** [pikax/swgoh#4]
When entering a username for a mod, I am getting the following error:

```
Uncaught Promise Error:  TypeError: Cannot read property 'startsWith' of undefined
    at Swgoh.<anonymous> (/Users/richiegirardin/GitHub/mouse-bot/node_modules/swgoh/dist/index.js:419:34)
    at step (/Users/richiegirardin/GitHub/mouse-bot/node_modules/swgoh/dist/index.js:74:23)
    at Object.next (/Users/richiegirardin/GitHub/mouse-bot/node_modules/swgoh/dist/index.js:55:53)
    at fulfilled (/Users/richiegirardin/GitHub/mouse-bot/node_modules/swgoh/dist/index.js:45:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

It used to work before, but does not now.

**Comment by pikax** [comment]
it seems the swgoh.gg change slightly the css of website, I made a commit that fix that issue

**Comment by pikax** [comment]
update to v0.3.2
